// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVNwcm5e5UwmL8-Bau4EAi3njrqERpQtg',
    appId: '1:832325767110:web:2518a3c9b23eeb53d6ecc7',
    messagingSenderId: '832325767110',
    projectId: 'pluto-games-822c0',
    authDomain: 'pluto-games-822c0.firebaseapp.com',
    storageBucket: 'pluto-games-822c0.appspot.com',
    measurementId: 'G-0Q0R01SWJJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClGJnO57fEVs4eOukhUyQz6vei6OAy9vI',
    appId: '1:832325767110:android:0348798c9ed2961ed6ecc7',
    messagingSenderId: '832325767110',
    projectId: 'pluto-games-822c0',
    storageBucket: 'pluto-games-822c0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjE8RL4LjegGnX_wOuvWBwFlXOePIimnI',
    appId: '1:832325767110:ios:c8a10447d1ca3cf3d6ecc7',
    messagingSenderId: '832325767110',
    projectId: 'pluto-games-822c0',
    storageBucket: 'pluto-games-822c0.appspot.com',
    iosBundleId: 'com.example.plutoGames',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBjE8RL4LjegGnX_wOuvWBwFlXOePIimnI',
    appId: '1:832325767110:ios:316cf52aa42dc4f8d6ecc7',
    messagingSenderId: '832325767110',
    projectId: 'pluto-games-822c0',
    storageBucket: 'pluto-games-822c0.appspot.com',
    iosBundleId: 'com.example.plutoGames.RunnerTests',
  );
}
